server:
  port: ${TASK_PORT:8081}

kafka:
  topic-names:
    project-delete: project-deleted-events-topic

spring:
  application:
    name: task-service

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://${PG_HOST}:5432/${PG_DATABASE}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      bootstrap-servers: ${BOOTSTRAP_HOST_1:localhost}:${BOOTSTRAP_PORT_1:9092},${BOOTSTRAP_HOST_2:localhost}:${BOOTSTRAP_PORT_2:9094}
      isolation-level: READ_COMMITTED

logging:
  level:
    org:
      springframework:
        kafka: TRACE
        transaction: TRACE