services:
  kafka-1:
    image: bitnami/kafka:latest
    container_name: kafka-1
    restart: "no"
    ports:
      - "${KAFKA_1_PORT}:9092"
    volumes:
      - kafka-1_data:/bitnami/kafka
    environment:
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT_HOST://${KAFKA_LISTENER_HOST}:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_REPLICATION}
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT_HOST
      KAFKA_CFG_NODE_ID: 1
      KAFKA_KRAFT_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:${KAFKA_CONTROLLER_PORT_1},2@kafka-2:${KAFKA_CONTROLLER_PORT_2}
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://0.0.0.0:${KAFKA_CONTROLLER_PORT_1}
    healthcheck:
      test: kafka-topics.sh --bootstrap-server localhost:9092 --list
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5

  kafka-2:
    image: bitnami/kafka:latest
    container_name: kafka-2
    restart: "no"
    ports:
      - "${KAFKA_2_PORT}:9094"
    volumes:
      - kafka-2_data:/bitnami/kafka
    environment:
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT_HOST://${KAFKA_LISTENER_HOST}:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_REPLICATION}
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT_HOST
      KAFKA_CFG_NODE_ID: 2
      KAFKA_KRAFT_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:${KAFKA_CONTROLLER_PORT_1},2@kafka-2:${KAFKA_CONTROLLER_PORT_2}
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT_HOST://0.0.0.0:9094,CONTROLLER://0.0.0.0:${KAFKA_CONTROLLER_PORT_2}
    healthcheck:
      test: kafka-topics.sh --bootstrap-server localhost:9094 --list
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: "no"
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: web-chat
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: "no"
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/

volumes:
  kafka-1_data:
  kafka-2_data:
  mongodb_data: