server:
  port: ${CHAT_PORT:8083}

websocket:
  endpoints: /ws
  allow-origins: ${ALLOW_ORIGIN:http://localhost:3000}
  application-destination-prefix: ${WEBSOCKET_APP_PREFIX:/app}
  broker-destination-prefix: ${WEBSOCKET_BROKER_PREFIX:/topic}
  user-destination-prefix: ${WEBSOCKET_USER_PREFIX:/user}

spring:
  application:
    name: chat-service

  data:
    mongodb:
      uri: mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE:web-chat}

logging:
  level:
    org:
      springframework:
        web:
          socket: DEBUG
        messaging: DEBUG