server:
  port: ${GATEWAY_PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: task-service
          uri: http://${TASK_HOST:localhost}:${TASK_PORT:8081}
          predicates:
            - Path=/api/tasks/**
          filters:
            - StripPrefix=1

        - id: project-service
          uri: http://${PROJECT_HOST:localhost}:${PROJECT_PORT:8082}
          predicates:
            - Path=/api/projects/**
          filters:
            - StripPrefix=1

        - id: chat-service
          uri: http://${CHAT_HOST:localhost}:${CHAT_PORT:8083}
          predicates:
            - Path=/api/chat/**
          filters:
            - StripPrefix=1

        - id: auth-service
          uri: http://${AUTH_HOST:localhost}:${AUTH_PORT:8084}
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always