server:
  port: ${AUTH_PORT:8084}

kafka:
  topic-names:
    user-create: user-created-events-topic
    user-update: user-updated-events-topic
    user-delete: user-deleted-events-topic

jwt:
  secret: ${JWT_SECRET}
  lifetime: ${JWT_LIFETIME:7d}

oauth2:
  redirect-url: ${OAUTH2_REDIRECT_URL:http://localhost:3000/login/oauth2/code/}

spring:
  application:
    name: auth-service

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    url: jdbc:postgresql://${PG_HOST}:5432/${PG_DATABASE}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 100
      properties:
        enable:
          idempotence: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: http://${GATEWAY_HOST:localhost}:${GATEWAY_PORT:8080}/api/login/oauth2/code/github
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://${GATEWAY_HOST:localhost}:${GATEWAY_PORT:8080}/api/login/oauth2/code/google
          yandex:
            client-id: ${YANDEX_CLIENT_ID}
            client-secret: ${YANDEX_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://${GATEWAY_HOST:localhost}:${GATEWAY_PORT:8080}/api/login/oauth2/code/yandex
            scope: login:email, login:info
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info
            user-name-attribute: id