DROP TABLE IF EXISTS avatar, project CASCADE;

CREATE TABLE IF NOT EXISTS project(
   id_project UUID PRIMARY KEY,
   name VARCHAR(50) NOT NULL,
   description TEXT NOT NULL DEFAULT 'Описание отсутствует.',
   date_added DATE DEFAULT current_date,
   date_updated DATE NOT NULL DEFAULT current_date,
   id_user BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS avatar(
    id_avatar BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    content_type VARCHAR(20) NOT NULL,
    size BIGINT NOT NULL CHECK ( size > 0 ),
    binary_data BYTEA NOT NULL,
    date_added DATE NOT NULL DEFAULT current_date,
    id_project UUID REFERENCES project(id_project)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- For kafka idempotent consumer
CREATE TABLE IF NOT EXISTS processed_event(
    id_event BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    message_id UUID NOT NULL,
    user_id BIGINT
);

CREATE INDEX message_idx ON processed_event USING HASH(message_id);